import numpy as np

INPUT = [
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 450,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 400,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 140,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "David",
        "party": "rogue",
        "candidatevotes": 10,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 375,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 600,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Dana",
        "party": "green",
        "candidatevotes": 25,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 400,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 550,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 50,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 400,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 525,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 50,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Daphne",
        "party": "peace",
        "candidatevotes": 25,
        "totalvotes": 1000,
    },
]

OUTPUT = [
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 450,
        "totalvotes": 1000,
        "vote_percent": 0.45,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 400,
        "totalvotes": 1000,
        "vote_percent": 0.4,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 140,
        "totalvotes": 1000,
        "vote_percent": 0.14,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "David",
        "party": "rogue",
        "candidatevotes": 10,
        "totalvotes": 1000,
        "vote_percent": 0.01,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 375,
        "totalvotes": 1000,
        "vote_percent": 0.375,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 600,
        "totalvotes": 1000,
        "vote_percent": 0.6,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Dana",
        "party": "green",
        "candidatevotes": 25,
        "totalvotes": 1000,
        "vote_percent": 0.025,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 400,
        "totalvotes": 1000,
        "vote_percent": 0.40,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 550,
        "totalvotes": 1000,
        "vote_percent": 0.55,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 50,
        "totalvotes": 1000,
        "vote_percent": 0.05,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 400,
        "totalvotes": 1000,
        "vote_percent": 0.4,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 525,
        "totalvotes": 1000,
        "vote_percent": 0.525,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 50,
        "totalvotes": 1000,
        "vote_percent": 0.05,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Daphne",
        "party": "peace",
        "candidatevotes": 25,
        "totalvotes": 1000,
        "vote_percent": 0.025,
    },
]
