import numpy as np

PRESIDENT = [
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 450,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 400,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 140,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "AL",
        "candidate": "David",
        "party": "rogue",
        "candidatevotes": 10,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 375,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 600,
        "totalvotes": 1000,
    },
    {
        "year": 2016,
        "state": "NJ",
        "candidate": "Dana",
        "party": "green",
        "candidatevotes": 25,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 400,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 550,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "AL",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 50,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Bob",
        "party": "republican",
        "candidatevotes": 400,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Alice",
        "party": "democrat",
        "candidatevotes": 425,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Charlie",
        "party": "libertarian",
        "candidatevotes": 50,
        "totalvotes": 1000,
    },
    {
        "year": 2012,
        "state": "NJ",
        "candidate": "Daphne",
        "party": "peace",
        "candidatevotes": 25,
        "totalvotes": 1000,
    },
]
